services:
  app:
    build: .
    container_name: app_socialite
    volumes: [".:/var/www"]
    networks: [socialite_net]
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks: [socialite_net]
networks:
  socialite_net:
    driver: bridge